# Generated by Django 3.0.6 on 2020-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=100)),
                ('isCompleted', models.BooleanField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
