# Generated by Django 3.0.6 on 2020-05-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unique.todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isCompleted',
            field=models.BooleanField(default='False'),
        ),
    ]
